
CREATE TABLE IF NOT EXISTS user (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

